M2Link/Controllers/RegisterController.cs
using M2Link.Repositories;
using M2Link.Services;
using M2Link.Services.Commands;
using M2Link.WebSite.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace M2Link.WebSite.Controllers
{
    public class RegisterController : M2LinkController
    {
        private readonly UserQueryService _userQueryService;
        private readonly UserCommandService _userCommandService;
        public RegisterController() : base()
        {
            _userQueryService = new UserQueryService();
            _userCommandService = new UserCommandService();
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Form()
        {
            return View(new RegisterModel());
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Form(RegisterModel model)
        {
         
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (_userQueryService.Exists(model.Pseudo))
            {
                ModelState.AddModelError("Pseudo", "Cet utilisateur existe déjà");
                return View(model);
            }

            try
            {
				byte[] img = null;
                if (model.File != null && model.File.ContentLength > 0)
                {
					Stream fs = model.File.InputStream;
					fs.Position = 0;
					BinaryReader br = new BinaryReader(fs);
					img = br.ReadBytes((Int32)fs.Length);
				}

				

                _userCommandService.Create(new UserCommand
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    Pseudo = model.Pseudo,
                    Password = model.Password,
                    Description = model.Description,
					Byte = img,
					ContentType = model.File?.ContentType
                });
            }
            catch
            {
                ModelState.AddModelError("File", "Erreur lors de l'upload");
                return View(model);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

M2Link/Controllers/UsersController.cs
using M2Link.WebSite.ViewModels;
using System;
using System.Configuration;
using System.IO;
using System.Web.Mvc;
using System.Web.Security;
using M2Link.Repositories;
using M2Link.Services;
using M2Link.Services.Commands;
using M2Link.Services.Data;

namespace M2Link.WebSite.Controllers
{
    public class UsersController : M2LinkController
    {
        private readonly UserQueryService _userQueryService;
        private readonly UserCommandService _userCommandService;
        public UsersController() : base()
        {
            _userQueryService = new UserQueryService();
            _userCommandService = new UserCommandService();
        }

        // GET: Index

        // Recupère la liste des users
        [HttpGet]
        public ActionResult Index()
        {
            return View(DataToModel(_userQueryService.GetFollowedAndFollowable(UserId)));
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _userQueryService.GetByPseudo(model.Pseudo);
                if (user == null)
                {
                    ModelState.AddModelError("Pseudo", "Cet utilisateur n'existe pas");
                }
                else if (!_userQueryService.CorrectPassword(model.Password, user.PasswordHash, user.PasswordSalt))
                {
                    ModelState.AddModelError("Password", "Mot de passe incorect");
                }
                else
                {
                    FormsAuthentication.SetAuthCookie(user.Id.ToString(), false);
                    return RedirectToAction("Index", "Home");
                }
            }

            return View("Login", model);
        }

        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return Json(new { Url = "/Home/Index" });
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View(DataToModel(_userQueryService.GetById(UserId)));
        }

        [HttpPost]
        public ActionResult Edit(EditUserModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
				byte[] img = null;
				if (model.File != null && model.File.ContentLength > 0)
				{
						Stream fs = model.File.InputStream;
						fs.Position = 0;
						BinaryReader br = new BinaryReader(fs);
						img = br.ReadBytes((Int32)fs.Length);
				}

				_userCommandService.Edit(new UserCommand
                {
                    Id = UserId,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Pseudo = model.Pseudo,
                    Email = model.Email,
                    Description = model.Description,
					Byte = img,
					ContentType = model.File?.ContentType
				});
            }
            catch
            {
                ModelState.AddModelError("File", "Erreur lors de l'upload");
                return View(model);
            }


            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Details(Guid id)
        {
            return View(DataToModel(_userQueryService.GetUserDetails(UserId, id)));
        }


        [HttpPost]
        public ActionResult Follow(Guid subscriptionId)
        {
            var pseudo = _userCommandService.Follow(new FollowCommand
            {
                UserId = UserId,
                SubscriptionId = subscriptionId
            });

            return Json(new { Message = "Vous venez de suivre " + pseudo });
        }

        [HttpPost]
        public ActionResult Unfollow(Guid subscriptionId)
        {
            var pseudo = _userCommandService.Unfollow(new FollowCommand
            {
                UserId = UserId,
                SubscriptionId = subscriptionId
            });

            return Json(new { Message = "Vous ne suivez plus " + pseudo });
        }

        public ActionResult AvatarUrl()
        {
			return Json(new { _userQueryService.GetById(UserId).ImageUrl }, JsonRequestBehavior.AllowGet);
        }

    }
}

M2Link/Views/Register/Form.cshtml
@model RegisterModel

@{
    ViewBag.Title = "S'inscrire";
}

<div class="register-page-container">

    @using (Html.BeginForm("Form", "Register", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="register-container">
            <div class="register-header text-center">S'inscrire</div>
            <div class="register-body">
                <div class="form-group form-register">
                    @Html.LabelFor(m => m.FirstName)
                    @Html.EditorFor(m => m.FirstName)
                    @Html.ValidationMessage("FirstName", new { @class = "text-danger" })
                </div>
                <div class="form-group form-register">
                    @Html.LabelFor(m => m.LastName)
                    @Html.EditorFor(m => m.LastName)
                    @Html.ValidationMessage("LastName", new { @class = "text-danger" })
                </div>
                <div class="form-group form-register">
                    @Html.LabelFor(m => m.Email)
                    @Html.EditorFor(m => m.Email)
                    @Html.ValidationMessage("Email", new { @class = "text-danger" })
                </div>
                <div class="form-group form-register">
                    @Html.LabelFor(m => m.Pseudo)
                    @Html.EditorFor(m => m.Pseudo)
                    @Html.ValidationMessage("Pseudo", new { @class = "text-danger" })
                </div>
                <div class="form-group form-register">
                    @Html.LabelFor(m => m.Description)
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                    @Html.ValidationMessage("Description", new { @class = "text-danger" })
                </div>
                <div class="form-group form-register">
                    @Html.LabelFor(m => m.Password)
                    @Html.EditorFor(m => m.Password)
                    @Html.ValidationMessage("Password", new { @class = "text-danger" })
                </div>
                <div class="form-group form-register">
                    @Html.LabelFor(m => m.VerifyPassword)
                    @Html.EditorFor(m => m.VerifyPassword)
                    @Html.ValidationMessage("VerifyPassword", new { @class = "text-danger" })
                </div>
                <div class="form-group form-register">
                    <div class="custom-file">
                        @Html.LabelFor(model => model.File)
                        @Html.TextBoxFor(m => m.File, new { type = "file", @class = "custom-file-input" })
                        @Html.ValidationMessage("File", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="margin-top-lg text-center">
                    <button type="submit" class="btn m2-button margin-right-md">S'inscrire</button>
                    @Html.ActionLink("Se connecter", "Login", "Users", null, new { @class = "btn m2-button " })
                </div>
            </div>
        </div>
    }
</div>