M2Link/Controllers/MessagesController.cs
using M2Link.Services;
using M2Link.Services.Commands;
using M2Link.WebSite.ViewModels;
using System;
using System.Web.Mvc;

namespace M2Link.WebSite.Controllers
{
    public class MessagesController : M2LinkController
    {
        private readonly LikeCommandService _likeCommandService;
        private readonly LikeQueryService _likeQueryService;
        private readonly MessageCommandService _messageCommandService;
        private readonly MessageQueryService _messageQueryService;
        public MessagesController()
        {
            _likeCommandService = new LikeCommandService();
            _likeQueryService = new LikeQueryService();
            _messageCommandService = new MessageCommandService();
            _messageQueryService = new MessageQueryService();
        }

        [HttpGet]
        public ActionResult Details(Guid id)
        {
            return View(DataToModel(_messageQueryService.GetById(id, UserId)));
        }

        [HttpPost]
        public ActionResult Create(string content)
        {
            var result = true;
            if (content == null || content.Length == 0)
            {
                result = false;
            }
            else
            {
                _messageCommandService.Create(new MessageCommand
                {
                    Content = content,
                    UserId = UserId
                });
            }

            return Json(new { result });
        }

        [HttpGet]
        public ActionResult GetLikes(Guid messageId)
        {
            return Json(new
            {
                Data = _likeQueryService.GetLikes(messageId)
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Like(Guid messageId)
        {

            var result = _likeCommandService.Create(new LikeCommand
            {
                MessageId = messageId,
                UserId = UserId
            });

            return Json(new 
            { 
                result.Success,
                Count = result.Value
            });
        }

        [HttpPost]
        public ActionResult Dislike(Guid messageId)
        {
            var result = _likeCommandService.Delete(new LikeCommand
            {
                MessageId = messageId,
                UserId = UserId
            });

            return Json(new 
            { 
                result.Success,
                Count = result.Value
            });
        }

        public ActionResult Timeline()
        {
            return Json(new { Data = DataToModel(_messageQueryService.GetTimeline(UserId)) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UserMessages(Guid userId)
        {
			return Json(new { Data = DataToModel(_messageQueryService.GetUserMessages(userId, UserId)) }, JsonRequestBehavior.AllowGet);
        }
    }
}

M2Link/Views/Shared/_Date.cshtml
@model DateTime

<p>le @Model.ToShortDateString() à @Model.ToShortTimeString()</p>

M2Link/Views/Shared/_Layout.cshtml
@using M2Link.WebSite.Util

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - M2Link</title>
	@Styles.Render("~/Content/css")
	@Styles.Render("~/Content/fontawesome")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/toastr")
	@Styles.Render("~/Content/datatables")
	<meta http-equiv="refresh" content="600">
</head>
<body>
	<ul class="nav nav-pills nav-stacked nav-m2link">


		@if (!Context.User.Identity.IsAuthenticated)
		{
			<li role="presentation" data-toggle="tooltip" data-placement="bottom" title="S'inscrire" class="@Html.IsActive("Form", "Register")">
				<a href="@Url.Action("Form", "Register")"><i class="glyphicon glyphicon-registration-mark"></i></a>
			</li>
			<li role="presentation" data-toggle="tooltip" data-placement="bottom" title="Se connecter" class="@Html.IsActive("Login", "Users")">
				<a href="@Url.Action("Login", "Users")"><i class="glyphicon glyphicon-log-in"></i></a>
			</li>
		}
		else
		{
			<li role="presentation" data-toggle="tooltip" data-placement="bottom" title="Accueil" class="@Html.IsActive("Index", "Home")">
				<a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i></a>
			</li>
			<li role="presentation" data-toggle="tooltip" data-placement="bottom" title="Utilisateurs" class="@Html.IsActive("Index", "Users")">
				<a href="@Url.Action("Index", "Users", User.Identity.Name)"><i class="fa fa-users"></i></a>
			</li>
			<li role="presentation" data-toggle="tooltip" data-placement="bottom" title="Profil" class="@Html.IsActive("Edit", "Users")">
				<a href="@Url.Action("Edit", "Users")"><i class="glyphicon glyphicon-user"></i></a>
			</li>
			<li role="presentation" data-toggle="tooltip" data-placement="bottom" title="Se déconnecter">
				<a id="logOut"><i class="glyphicon glyphicon-log-out"></i></a>
			</li>
		}
		<li role="presentation" data-toggle="tooltip" data-placement="bottom" title="Aide" class="@Html.IsActive("Help", "Home")">
			<a href="@Url.Action("Help", "Home")"><i class="fa fa-question-circle"></i></a>
		</li>
	</ul>
	<div class="container body-content">
		@RenderBody()
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/toastr")
	@Scripts.Render("~/bundles/datatables")
	@Scripts.Render("~/bundles/site")
	@RenderSection("scripts", required: false)
</body>
</html>

M2Link/Views/Shared/_Messages.cshtml
@model MessagesModel

<div class="row">
    @if (Model.Messages.Any())
    {
        foreach (var message in Model.Messages)
        {
            <div class="message-container col-md-12 margin-bottom-md" data-action="@Url.Action("Details", "Messages", new { id = message.Id })">
                <div class="margin-top-sm">
                    <img class="rounded-messages" src="@Url.Content(message.ImageUrl ?? "")" alt="profile picture" />
                    <strong> @message.UserFirstName @message.UserLastName</strong> (@Html.ActionLink("@" + message.UserPseudo, "Details", "Users", new { id = message.UserId }, null))
                </div>
                <p class="margin-left-xl"> @message.Content</p>
                <div class="text-right small text-muted">
                    <div class="inline-block margin-right-md like-color">
                        <div>
                            <input type="hidden" value="@message.Id" />
                            <p class="inline-block counter">
                                @message.Likes.Count
                            </p>
                            <i class="inline-block fa fa-heart like @(message.IsLiked ? "liked" : "")"></i>
                        </div>
                    </div>
                    <div class="inline-block">
                        @Html.Partial("_Date", message.CreatedAt)
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <p>Aucun message</p>
    }

</div>